services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    network_mode: service:db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.20-bookworm
        NODE_VERSION: "lts/*"
    env_file:
      - .env
    volumes:
      - ../.:/workspace:cached
    command: sleep infinity
    restart: unless-stopped
    depends_on:
      - db
    network_mode: service:db

volumes:
  db-data:
  redis-data: