services:
  hkp0:
    build:
      context: ../../..
    ports:
    - "11400:11370"
    - "11401:11371"
    restart: always
    depends_on:
    - pg0
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - PKS
    - PKSFAILOVER
    - SPLIT_BRAIN
    - ENUM_DOMAINS_02
    volumes:
    - ./hkp0/etc:/hockeypuck/etc:ro
    - ./hkp0/keydump${HKP0_DIR_SUFFIX:-}:/hockeypuck/import/dump:ro
    - hkp0_data${HKP0_DIR_SUFFIX:-}:/hockeypuck/data
    networks:
      vpcbr:
        ipv4_address: 10.155.1.0
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

  pg0:
    image: postgres:17
    restart: always
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    volumes:
    - pg0_data${HKP0_DIR_SUFFIX:-}:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.155.2.0

  hkp1:
    image: testswarm-hkp0
    ports:
    - "11410:11370"
    - "11411:11371"
    restart: always
    depends_on:
    - pg1
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - PKS
    - PKSFAILOVER
    - ENUM_DOMAINS_13
    volumes:
    - ./hkp1/etc:/hockeypuck/etc:ro
    - ./hkp1/keydump${HKP1_DIR_SUFFIX:-}:/hockeypuck/import/dump:ro
    - hkp1_data${HKP1_DIR_SUFFIX:-}:/hockeypuck/data
    networks:
      vpcbr:
        ipv4_address: 10.155.1.1
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

  pg1:
    image: postgres:16
    restart: always
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    volumes:
    - pg1_data${HKP1_DIR_SUFFIX:-}:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.155.2.1

  hkp2:
    image: testswarm-hkp0
    ports:
    - "11420:11370"
    - "11421:11371"
    restart: always
    depends_on:
    - pg2
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - PKS
    - PKSFAILOVER
    - ENUM_DOMAINS_02
    volumes:
    - ./hkp2/etc:/hockeypuck/etc:ro
    - ./hkp2/keydump${HKP2_DIR_SUFFIX:-}:/hockeypuck/import/dump:ro
    - hkp2_data${HKP2_DIR_SUFFIX:-}:/hockeypuck/data
    networks:
      vpcbr:
        ipv4_address: 10.155.1.2
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

  pg2:
    image: postgres:15
    restart: always
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    volumes:
    - pg2_data${HKP2_DIR_SUFFIX:-}:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.155.2.2

  hkp3:
    image: testswarm-hkp0
    ports:
    - "11430:11370"
    - "11431:11371"
    restart: always
    depends_on:
    - pg3
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - PKS
    - PKSFAILOVER
    - PKS_3TO1
    - ENUM_DOMAINS_13
    volumes:
    - ./hkp3/etc:/hockeypuck/etc:ro
    - ./hkp3/keydump${HKP3_DIR_SUFFIX:-}:/hockeypuck/import/dump:ro
    - hkp3_data${HKP3_DIR_SUFFIX:-}:/hockeypuck/data
    networks:
      vpcbr:
        ipv4_address: 10.155.1.3
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

  pg3:
    image: postgres:14
    restart: always
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    volumes:
    - pg3_data${HKP3_DIR_SUFFIX:-}:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.155.2.3

volumes:
  hkp0_data: {}
  pg0_data: {}
  hkp1_data: {}
  pg1_data: {}
  hkp2_data: {}
  pg2_data: {}
  hkp3_data: {}
  pg3_data: {}
  hkp2_data.scenario4: {}
  pg2_data.scenario4: {}
  hkp3_data.scenario5: {}
  pg3_data.scenario5: {}
  hkp0_data.scenario6: {}
  pg0_data.scenario6: {}
  hkp1_data.scenario6: {}
  pg1_data.scenario6: {}
  hkp2_data.scenario6: {}
  pg2_data.scenario6: {}
  hkp3_data.scenario6: {}
  pg3_data.scenario6: {}

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.155.0.0/16
         gateway: 10.155.0.1
